# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  better-calibrator = {
    pname = "better-calibrator";
    version = "0.2.0";
    src = fetchTarball {
      url = "https://github.com/TheBlueOompaLoompa/BetterCalibrator/releases/download/0.2.0/BetterCalibrator.zip";
      sha256 = "sha256-ZNHuoZwBqzhIZywx3OcF4T5vSh8HXdA8nTkfnb5F13Y=";
    };
  };
}
